Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: '单机版'
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
  DeployMetadata:
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::LYH-RAIN_twenty-docker-compose }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-beijing
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker compose deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: LYH-RAIN_twenty-docker-compose
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/docker_compose.tar'
  Artifact_2:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-ubuntu
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_1.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_1.Tag}
      RepoType: Public
  Artifact_3:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-twentycrm-twenty
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_2.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_2.Tag}
      RepoType: Public
  Artifact_4:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-twentycrm-twenty
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_3.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_3.Tag}
      RepoType: Public
  Artifact_5:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-twentycrm-twenty-postgres
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_4.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_4.Tag}
      RepoType: Public
  Artifact_6:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-redis
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_5.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_5.Tag}
      RepoType: Public
AcrImageBuilder:
  AcrImage_1:
    BuildType: DockerRepo
    DockerRepoUrl: ubuntu
    RepoName: ubuntu
    Tag: latest
  AcrImage_2:
    BuildType: DockerRepo
    DockerRepoUrl: twentycrm/twenty:${TAG}
    RepoName: twentycrm/twenty
    Tag: ${TAG}
  AcrImage_3:
    BuildType: DockerRepo
    DockerRepoUrl: twentycrm/twenty:${TAG}
    RepoName: twentycrm/twenty
    Tag: ${TAG}
  AcrImage_4:
    BuildType: DockerRepo
    DockerRepoUrl: twentycrm/twenty-postgres:${TAG}
    RepoName: twentycrm/twenty-postgres
    Tag: ${TAG}
  AcrImage_5:
    BuildType: DockerRepo
    DockerRepoUrl: redis
    RepoName: redis
    Tag: latest